# Generated by Django 2.1 on 2018-09-07 06:16

from django.db import migrations, models
import django.db.models.deletion
import main_website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('maintenance_id', models.AutoField(primary_key=True, serialize=False)),
                ('maintenance_status', models.CharField(choices=[('0', 'Ok'), ('1', 'At Repairer'), ('2', 'With Staff Member')], max_length=1)),
                ('maintenance_location', models.CharField(max_length=255)),
                ('maintenance_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('membership_type', models.CharField(choices=[('g', 'Guest'), ('r', 'Regular'), ('l', 'Librarian')], default='g', max_length=1)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('maillist', models.BooleanField(default=True)),
                ('telephone_num', models.CharField(max_length=15)),
                ('address', models.TextField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=4)),
                ('country', models.CharField(max_length=30)),
                ('balance', models.FloatField(default=0)),
                ('suburb', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('membership', models.OneToOneField(default=main_website.models.Member.get_new, on_delete=django.db.models.deletion.CASCADE, to='main_website.Member')),
            ],
        ),
    ]
