# Generated by Django 2.1 on 2018-10-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(null=True, upload_to='products'),
        ),
    ]
