# Generated by Django 2.1 on 2018-09-07 04:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
import main_website.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('membership', models.CharField(choices=[('g', 'Guest'), ('r', 'Regular'), ('l', 'Librarian')], default='g', max_length=1)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Start')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='End')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscriber', models.BooleanField(default=True)),
                ('telephone', models.CharField(max_length=15)),
                ('street', models.TextField()),
                ('city', models.CharField(max_length=30)),
                ('county', models.CharField(max_length=30)),
                ('postcode', models.CharField(max_length=4)),
                ('country', models.CharField(max_length=30)),
                ('balance', models.FloatField()),
                ('suburb', models.CharField(max_length=30)),
                ('membership', models.OneToOneField(default=main_website.models.Member.get_new, on_delete=django.db.models.deletion.CASCADE, to='main_website.Member')),
            ],
        ),
        migrations.RemoveField(
            model_name='semester',
            name='courses',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
