# Generated by Django 2.1 on 2018-10-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_verified',
            field=models.BooleanField(default=False),
        ),
    ]
