# Generated by Django 2.1 on 2018-10-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='start_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
