# Generated by Django 2.1 on 2018-10-07 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lending',
            old_name='productStatus',
            new_name='product_status',
        ),
        migrations.RenameField(
            model_name='lendinghistory',
            old_name='productStatus',
            new_name='product_status',
        ),
    ]
