# Generated by Django 2.1 on 2018-09-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0002_auto_20180919_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lending',
            options={'verbose_name': 'Loan'},
        ),
        migrations.AlterModelOptions(
            name='lendinghistory',
            options={'verbose_name': 'Loan history', 'verbose_name_plural': 'Loan histories'},
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
