# Generated by Django 2.1 on 2018-09-09 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0002_auto_20180909_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_website.ProductCondition'),
        ),
    ]
