# Generated by Django 2.1 on 2018-09-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0002_auto_20180907_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.TextField(max_length=30),
        ),
    ]
