# Generated by Django 2.1 on 2018-10-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0003_auto_20181024_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_identified',
            field=models.BooleanField(default=False, help_text='Member uploaded identification ID is correct'),
        ),
    ]
