# Generated by Django 2.1 on 2018-10-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0003_ordernotes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderNotes',
            new_name='OrderNote',
        ),
    ]
