# Generated by Django 2.1 on 2018-09-11 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0004_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductTags',
            new_name='ProductTag',
        ),
    ]
