# Generated by Django 2.1 on 2018-09-24 13:17

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main_website.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0004_openinghour'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificationImage',
            fields=[
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='identification', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.FileField(upload_to=main_website.models.user_directory_path)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='has_identified',
            field=models.BooleanField(default=False),
        ),
    ]
