# Generated by Django 2.1 on 2018-09-24 13:48

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0005_auto_20180924_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='member',
            field=annoying.fields.AutoOneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membershipType', to='main_website.Member'),
        ),
    ]
