# Generated by Django 2.1 on 2018-09-10 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0005_auto_20180910_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='membership', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
