# Generated by Django 2.1 on 2018-09-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0005_auto_20180925_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingday',
            name='opening_day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
    ]
