# Generated by Django 2.1 on 2018-09-11 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_website', '0005_auto_20180911_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('productStatus', models.CharField(choices=[('ONLOAN', 'ONLOAN'), ('RETURNTODAY', 'RETURNTODAY'), ('RETURNLATE', 'RETURNLATE'), ('RESERVED', 'RESERVED'), ('COLLECTTODAY', 'COLLECTTODAY'), ('COLLECTLATE', 'COLLECTLATE')], max_length=12)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_website.Product')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
