# Generated by Django 2.1 on 2018-09-11 11:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_website', '0006_calendar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calendar',
            new_name='Lending',
        ),
    ]
