# Generated by Django 2.1 on 2018-09-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0006_user_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='member',
        ),
    ]
