# Generated by Django 2.1 on 2018-10-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0006_auto_20181024_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingday',
            name='opening_day',
            field=models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')]),
        ),
    ]
