# Generated by Django 2.1 on 2018-09-19 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0005_auto_20180911_0436'),
        ('main_website', '0007_auto_20180910_1430'),
    ]

    operations = [
    ]
