# Generated by Django 2.1 on 2018-09-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0007_auto_20180910_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='county',
            field=models.CharField(max_length=30),
        ),
    ]
