# Generated by Django 2.1 on 2018-10-26 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0007_auto_20181025_0034'),
        ('main_website', '0002_product_main_image'),
    ]

    operations = [
    ]
