# Generated by Django 2.1 on 2018-09-14 05:45

from django.db import migrations, models
import main_website.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0007_auto_20180911_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending',
            name='endDate',
            field=models.DateField(validators=[main_website.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='lending',
            name='productStatus',
            field=models.CharField(choices=[('ONLOAN', 'ON LOAN'), ('RETURNTODAY', 'RETURN TODAY'), ('RETURNLATE', 'RETURN LATE'), ('RESERVED', 'RESERVED'), ('COLLECTTODAY', 'COLLECT TODAY'), ('COLLECTLATE', 'COLLECT LATE')], max_length=12),
        ),
        migrations.AlterField(
            model_name='lending',
            name='startDate',
            field=models.DateField(validators=[main_website.models.validate_date]),
        ),
    ]
