# Generated by Django 2.1 on 2018-09-19 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main_website.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_website', '0008_auto_20180914_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='LendingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(validators=[main_website.models.validate_date])),
                ('endDate', models.DateField(validators=[main_website.models.validate_date])),
                ('productStatus', models.CharField(choices=[('ONLOAN', 'ON LOAN'), ('RETURNTODAY', 'RETURN TODAY'), ('RETURNLATE', 'RETURN LATE'), ('RESERVED', 'RESERVED'), ('COLLECTTODAY', 'COLLECT TODAY'), ('COLLECTLATE', 'COLLECT LATE')], max_length=12)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_website.Product')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
