# Generated by Django 2.1 on 2018-09-18 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0008_auto_20180914_1340'),
        ('main_website', '0005_auto_20180911_0436'),
    ]

    operations = [
    ]
