# Generated by Django 2.1 on 2018-10-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0008_merge_20181026_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='openingday',
            name='opening_day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
    ]
